import request from './index'
import type { 
  Environment, 
  API, 
  TestData, 
  ExecutionRecord, 
  ExecuteRequest, 
  BatchExecuteRequest,
  BatchExecuteResult 
} from './types'

// 环境管理
export const getEnvironments = () => {
  return request.get<any, Environment[]>('/environments')
}

export const createEnvironment = (data: Partial<Environment>) => {
  return request.post<any, Environment>('/environments', data)
}

export const updateEnvironment = (id: number, data: Partial<Environment>) => {
  return request.put<any, Environment>(`/environments/${id}`, data)
}

export const deleteEnvironment = (id: number) => {
  return request.delete(`/environments/${id}`)
}

// Swagger上传
export const uploadSwagger = (file: File) => {
  const formData = new FormData()
  formData.append('file', file)
  return request.post('/swagger/upload', formData, {
    headers: {
      'Content-Type': 'multipart/form-data'
    }
  })
}

// 接口管理
export const getApis = (params?: { method?: string; tag?: string; limit?: number }) => {
  return request.get<any, API[]>('/apis', { params })
}

export const getApi = (id: number) => {
  return request.get<any, API>(`/apis/${id}`)
}

export const deleteApi = (id: number) => {
  return request.delete(`/apis/${id}`)
}

export const deleteAllApis = () => {
  return request.delete('/apis')
}

export const syncSwaggerFromUrl = (swaggerUrl?: string, autoGenerateData: boolean = true) => {
  return request.post<any, { message: string; deleted_count: number; imported_count: number; test_data_count: number; source_url: string }>('/swagger/sync', null, {
    params: {
      swagger_url: swaggerUrl || 'http://192.168.60.219:48080/v3/api-docs',
      auto_generate_data: autoGenerateData
    }
  })
}

// 测试数据管理
export const getTestDataList = (apiId?: number) => {
  return request.get<any, TestData[]>('/test-data', { 
    params: apiId ? { api_id: apiId } : undefined 
  })
}

export const getTestData = (id: number) => {
  return request.get<any, TestData>(`/test-data/${id}`)
}

export const createTestData = (data: Partial<TestData>) => {
  return request.post<any, TestData>('/test-data', data)
}

export const updateTestData = (id: number, data: Partial<TestData>) => {
  return request.put<any, TestData>(`/test-data/${id}`, data)
}

export const deleteTestData = (id: number) => {
  return request.delete(`/test-data/${id}`)
}

export const generateTestData = (apiId: number) => {
  return request.post<any, TestData>(`/test-data/generate/${apiId}`)
}

// 接口执行
export const executeApi = (apiId: number, data: ExecuteRequest) => {
  return request.post<any, ExecutionRecord>(`/execute/${apiId}`, data)
}

export const batchExecute = (data: BatchExecuteRequest) => {
  return request.post<any, BatchExecuteResult>('/execute/batch', data)
}

// 执行记录
export const getExecutionRecords = (apiId?: number) => {
  return request.get<any, ExecutionRecord[]>('/execution-records', {
    params: apiId ? { api_id: apiId } : undefined
  })
}

export const getExecutionRecord = (id: number) => {
  return request.get<any, ExecutionRecord>(`/execution-records/${id}`)
}

// 串联方案管理
export interface ChainPlan {
  id?: number
  name: string
  description?: string
  api_ids: number[]
  api_params?: Record<string, { query?: string; body?: string; headers?: string }>  // 参数配置
  api_assertions?: Record<string, Array<{
    type: 'status_code' | 'json_path' | 'response_time' | 'contains'
    path?: string
    operator: 'eq' | 'ne' | 'gt' | 'lt' | 'contains' | 'not_contains'
    expected: string
    result?: boolean
    actualValue?: string
  }>>  // 断言配置
  global_variables?: Record<string, any>  // 全局变量
  environment_id?: number
  stop_on_error: boolean
  delay_ms: number
  created_at?: string
  updated_at?: string
}

export const getChainPlans = () => {
  return request.get<any, ChainPlan[]>('/chain-plans')
}

export const getChainPlan = (id: number) => {
  return request.get<any, ChainPlan>(`/chain-plans/${id}`)
}

export const createChainPlan = (data: Omit<ChainPlan, 'id' | 'created_at' | 'updated_at'>) => {
  return request.post<any, ChainPlan>('/chain-plans', data)
}

export const updateChainPlan = (id: number, data: Partial<Omit<ChainPlan, 'id' | 'created_at' | 'updated_at'>>) => {
  return request.put<any, ChainPlan>(`/chain-plans/${id}`, data)
}

export const deleteChainPlan = (id: number) => {
  return request.delete(`/chain-plans/${id}`)
}

